language: python
os: linux
dist: trusty
sudo: required
compiler: gcc

matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: "3.6-dev"
    - python: "nightly"

  allow_failures:
    - python: "3.6-dev"
    - python: "nightly"

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - python-pip
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  global:
    - NO_NET=1

# start Virtual X, so default matplotlib backend works
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

# command to install dependencies
install:
    - if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir "$HOME/.local/bin";
      fi
    - export PATH="$HOME/.local/bin:$PATH"
    - ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran" && gfortran --version
    - ls -l /usr/bin/gfortran-6
    - if [[ $TRAVIS_PYTHON_VERSION < 3.3 ]];
      then pip install -r requirements2-34.travis.txt;
      fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]];
      then pip install -r requirements33.travis.txt;
      fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]];
      then pip install -r requirements2-34.travis.txt;
      fi
    - if [[ $TRAVIS_PYTHON_VERSION > 3.4 ]];
      then pip install -r requirements.travis.txt;
      fi
    - pip install https://github.com/modflowpy/pymake/zipball/master
    - pip install nose-timer
    - pip install coveralls


# command to run tests
script: 
    - export PYTHONPATH=$PYTHONPATH:.
    - python -c "import os; is_travis = 'TRAVIS' in os.environ; print('TRAVIS {}'.format(is_travis))"
    - echo numpy version; python -c "import numpy; print(numpy.version.version)"
    - nosetests -v --with-id --with-timer -w ./autotest --with-coverage --cover-package=flopy
after_success:
    - coveralls
