language: python
os: linux
dist: xenial
compiler: gcc

services:
  - xvfb

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: "3.7-dev"

  allow_failures:
    - python: "3.7-dev"

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-8
      - g++-8
      - python-pip
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
      - gdal-bin
      - libgdal-dev

env:
  global:
    - NO_NET=1

# command to install dependencies
install:
    - if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir "$HOME/.local/bin";
      fi
    - export PATH="$HOME/.local/bin:$PATH"
    - ln -fs /usr/bin/gfortran-8 "$HOME/.local/bin/gfortran" && gfortran --version
    - ls -l /usr/bin/gfortran-8
    - ln -fs /usr/bin/gcc-8 "$HOME/.local/bin/gcc" && gcc --version
    - ls -l /usr/bin/gcc-8
    - ln -fs /usr/bin/g++-8 "$HOME/.local/bin/g++" && g++ --version
    - ls -l /usr/bin/g++-8
    - export CXX="g++"
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
        pip install -r requirements27.travis.txt;
        echo requests version1; python -c "import requests; print(requests.__version__)";
      else
        pip install -r requirements.travis.txt;
      fi
    - pip install https://github.com/modflowpy/pymake/zipball/master
    - pip install --upgrade jupyter
    - pip install nbconvert
    - pip install nose-timer
    - pip install coveralls
    - pip install pylint


# command to run tests
script:
    - export PYTHONPATH=$PYTHONPATH:.
    - echo python path; python -c "from __future__ import print_function; import sys; print(sys.path)"
    - python -c "import os; is_travis = 'TRAVIS' in os.environ; print('TRAVIS {}'.format(is_travis))"
    - echo flopy version; python -c "from __future__ import print_function; import flopy; print(flopy.__version__)"
    - echo numpy version; python -c "import numpy; print(numpy.version.version)"
    - echo pandas version; python -c "import pandas as pd; print(pd.__version__)"
    - echo pyshp; python -c "import shapefile; print(shapefile.__version__)"
    - echo nosetests version; nosetests --version
    - echo jupyter version; jupyter --version
    - echo jupyter runtime directory; jupyter --runtime-dir
    - echo pylint version; pylint --version
    - cd ./autotest
    - python build_exes.py --travis --keep
    - cd ../
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
        nosetests -v autotest_scripts.py --with-id --with-timer -w ./autotest --with-coverage --cover-package=flopy;
      elif [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
        nosetests -v autotest_notebooks.py --with-id --with-timer -w ./autotest --with-coverage --cover-package=flopy;
      fi
    - nosetests -v --with-id --with-timer -w ./autotest --with-coverage --cover-package=flopy

after_success:
    - coveralls
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then
      pylint --errors-only ./flopy;
      fi
