language: python

sudo: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  global:
    - DEPENDS="cython>=0.19"
    - NO_NET=1

# 2.6 and "nightly" do not work at the moment, so they are commented out.
python:
  # - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  # - "nightly" # currently points to 3.6-dev

# start Virtual X, so default matplotlib backend works
before_install:
    - "pip install $DEPENDS"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

# command to install dependencies
install: "pip install -r requirements.travis.txt"

# command to run tests
script: 
    - export PYTHONPATH=$PYTHONPATH:.
    - nosetests -v -w ./autotest
