language: python

sudo: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  global:
    #- DEPENDS="cython>=0.19"
    - NO_NET=1

matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: "3.6-dev"
    - python: "nightly"

  allow_failures:
    - python: "3.6-dev"
    - python: "nightly"

# start Virtual X, so default matplotlib backend works
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

# command to install dependencies
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]];
      then pip install -r requirements33.travis.txt;
      else pip install -r requirements.travis.txt;
      fi


# command to run tests
script: 
    - export PYTHONPATH=$PYTHONPATH:.
    - echo numpy version; python -c "import numpy; print(numpy.version.version)"
    - nosetests -v -w ./autotest
