name: flopy
channels:
  - conda-forge
dependencies:
  - pylint
  - flake8
  - black
  - nose
  - nose-timer
  - coverage
  - appdirs
  - requests
  - numpy
  - matplotlib
  - bmipy
  - affine
  - scipy
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - fiona
  - descartes
  - pyproj
  - shapely
  - geos=3.8.1  # required until 3.9.2 is available
