name: flopy
channels:
  - conda-forge
dependencies:
  # required
  - python>=3.7
  - numpy>=1.15.0
  - matplotlib>=1.4.0

  # lint
  - black
  - flake8
  - isort
  - pylint

  # test
  - coverage
  - flaky
  - filelock
  - jupyter
  - jupytext
  - pytest
  - pytest-cases
  - pytest-cov
  - pytest-xdist
  - pytest-benchmark

  # optional
  - python-dateutil>=2.4.0
  - affine
  - scipy
  - pandas
  - netcdf4
  - pyshp
  - rasterio
  - fiona
  - descartes
  - pyproj
  - shapely>=1.8
  - geos
  - geojson
  - vtk
  - rasterstats

  # MODFLOW API dependencies
  - bmipy
