name: flopy
channels:
  - conda-forge
dependencies:
  # required
  - python>=3.7
  - numpy>=1.15.0
  - matplotlib>=1.4.0

  # testing
  - pylint
  - flake8
  - black
  - nose
  - nose-timer
  - coverage

  # optional
  - appdirs
  - python-dateutil>=2.4.0
  - affine
  - scipy
  - pandas
  - netcdf4
  - pyshp>=2.0.0
  - rasterio
  - fiona
  - descartes
  - pyproj
  - shapely
  - geos
  - geojson
  - vtk

  # external dependencies
  - requests

  # MODFLOW API dependencies
  - bmipy
